name: CI/CD Pipeline

on: push
env:
  SSH_KEY_PEM: ${{ secrets.SSH_KEY_PEM }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/example-k8s-github:latest

      - name: Deploy Backend
        run: |
          echo $SSH_KEY_PEM > ./ssh-key.pem
          chmod 600 ./ssh-key.pem
          ls -la
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ec2-user@ec2-3-70-99-149.eu-central-1.compute.amazonaws.com

  build_artifact:
    runs-on: ubuntu-latest
    needs: [build_and_deploy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies and Build Artifact
        run: |
          cd frontend
          npm install
          npm run build:prod
        working-directory: ./frontend
        env:
          NODE_ENV: production

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist/frontend/browser/

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [build_artifact]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: aws s3 sync frontend/dist/frontend/browser/ s3://${{ secrets.S3_BUCKET_NAME }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
